name: Update README

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run script to update README
        run: node .github/scripts/update-readme.js